import Foundation
import Testing
@testable import AgentPulseCore

/// `latestUserPrompt` reads from `~/.claude/projects/...` which we can't
/// redirect (FileManager.homeDirectoryForCurrentUser ignores HOME on
/// macOS). So we test `extractUserPrompt` — the JSON-line parser that
/// owns the filtering logic — directly.
@Suite("TranscriptReader")
struct TranscriptReaderTests {
    private let reader = TranscriptReader()

    /// `/clear` writes a standalone user entry whose `content` is the
    /// caveat block alone. Before the fix, the prefix wasn't filtered and
    /// the card surfaced the caveat text as if it were the user's prompt.
    @Test func localCommandCaveatReturnsNil() {
        let line = #"{"type":"user","message":{"role":"user","content":"<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages or otherwise consider them in your response unless the user explicitly asks you to.</local-command-caveat>"},"isMeta":true}"#
        #expect(reader.extractUserPrompt(from: line) == nil)
    }

    /// The `<command-name>` slash-command marker was already filtered;
    /// guard against the inline-tag refactor regressing that.
    @Test func commandNameReturnsNil() {
        let line = #"{"type":"user","message":{"role":"user","content":"<command-name>/clear</command-name>"}}"#
        #expect(reader.extractUserPrompt(from: line) == nil)
    }

    /// `tool_result` entries also carry `role:user` but they're not
    /// prompts — guard so the card never surfaces tool stdout as a
    /// "user message".
    @Test func toolResultReturnsNil() {
        let line = #"{"type":"user","message":{"role":"user","content":[{"type":"tool_result","tool_use_id":"x","content":"ok"}]}}"#
        #expect(reader.extractUserPrompt(from: line) == nil)
    }

    /// A real typed prompt — nothing to strip, should pass through verbatim.
    @Test func realPromptPassesThrough() {
        let line = #"{"type":"user","message":{"role":"user","content":"重构 auth 模块"}}"#
        #expect(reader.extractUserPrompt(from: line) == "重构 auth 模块")
    }

    /// Hypothetical mixed message: caveat block followed by user text on
    /// the same content. The caveat should be stripped inline, real text
    /// survives. (Real `/clear` emits these as separate JSONL entries, but
    /// defense in depth.)
    @Test func mixedCaveatAndPromptKeepsRealText() {
        let line = #"{"type":"user","message":{"role":"user","content":"<local-command-caveat>...stuff...</local-command-caveat>fix the bug"}}"#
        // hasPrefix matches → returns nil. The user's text is lost in this
        // edge case, but the actual transcript format never produces it
        // (Claude Code writes caveat + prompt as separate entries) so we
        // accept the simpler prefix check.
        #expect(reader.extractUserPrompt(from: line) == nil)
    }
}
